<?php
   $_data = $block->getAllOrderItems();
?>
<table calss="table">
    <thead>
        <tr>
            <th>Product ID</th>
            <th>Thumbnial</th>
            <th>Name</th>
            <th>Price</th>
            <th>Order IDs</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($_data as $item): ?>
        <tr>
            <td><?php echo $item['product_id'] ?></td>
            <td><img src="<?php echo $block->escapeUrl($item['thumbnail']) ?>" alt="<?php echo $item['name'] ?>"></td>
            <td><?php echo $item['name'] ?></td>
            <td><?php echo $item['price'] ?></td>
            <td><?php echo implode(",", $item['order_ids']) ?></td>
            <td>
               <a href="/<?php echo $item['url_key'] ?>.html">
                  <button>
                     Open
                  </button>
               </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
